package tools

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWorkspaceToolsRejectPathTraversal(t *testing.T) {
	root := t.TempDir()
	outside := filepath.Join(t.TempDir(), "secret.txt")
	if err := os.WriteFile(outside, []byte("secret"), 0o600); err != nil {
		t.Fatal(err)
	}

	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}

	_, err = workspace.ReadFile("../" + filepath.Base(outside))
	if err == nil {
		t.Fatal("expected path traversal read to fail")
	}
	if !strings.Contains(err.Error(), "outside workspace") {
		t.Fatalf("expected outside workspace error, got %v", err)
	}

	err = workspace.WriteFile("../escape.txt", "owned")
	if err == nil {
		t.Fatal("expected path traversal write to fail")
	}
	if _, statErr := os.Stat(filepath.Join(filepath.Dir(root), "escape.txt")); !os.IsNotExist(statErr) {
		t.Fatalf("write escaped workspace, stat err: %v", statErr)
	}
}

func TestWorkspaceToolsReadSearchWriteAndRun(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "main.txt"), []byte("hello coding agent\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}

	content, err := workspace.ReadFile("main.txt")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(content, "1\thello coding agent") {
		t.Fatalf("unexpected content %q", content)
	}

	matches, err := workspace.Search("coding")
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 1 || matches[0].Path != "main.txt" || matches[0].Line != 1 {
		t.Fatalf("unexpected matches: %#v", matches)
	}

	if err := workspace.WriteFile("generated.txt", "generated by agent\n"); err != nil {
		t.Fatal(err)
	}
	written, err := os.ReadFile(filepath.Join(root, "generated.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if string(written) != "generated by agent\n" {
		t.Fatalf("unexpected written content %q", string(written))
	}

	result, err := workspace.RunShell("cat generated.txt")
	if err != nil {
		t.Fatal(err)
	}
	if result.ExitCode != 0 || strings.TrimSpace(result.Stdout) != "generated by agent" {
		t.Fatalf("unexpected shell result: %#v", result)
	}
}

func TestWorkspaceReadRangeAndBinaryGuard(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "notes.txt"), []byte("one\ntwo\nthree\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "bin.dat"), []byte{'a', 0, 'b'}, 0o600); err != nil {
		t.Fatal(err)
	}
	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}

	content, err := workspace.ReadFileRange("notes.txt", 2, 1)
	if err != nil {
		t.Fatal(err)
	}
	if strings.TrimSpace(content) != "2\ttwo" {
		t.Fatalf("unexpected range content %q", content)
	}
	if _, err := workspace.ReadFile("bin.dat"); err == nil {
		t.Fatal("expected binary read to fail")
	}
}

func TestWorkspaceComplexFileTools(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "src", "pkg"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "src", "pkg", "main.go"), []byte("package main\nfunc main() {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}

	if err := workspace.Mkdir("docs"); err != nil {
		t.Fatal(err)
	}
	if err := workspace.AppendFile("docs/log.txt", "first\n"); err != nil {
		t.Fatal(err)
	}
	if err := workspace.AppendFile("docs/log.txt", "second\n"); err != nil {
		t.Fatal(err)
	}
	logData, err := os.ReadFile(filepath.Join(root, "docs", "log.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if string(logData) != "first\nsecond\n" {
		t.Fatalf("unexpected append result %q", string(logData))
	}

	matches, err := workspace.Glob("*.go", "src/pkg", false)
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 1 || matches[0] != "src/pkg/main.go" {
		t.Fatalf("unexpected glob matches %#v", matches)
	}

	tree, err := workspace.Tree(".", 3)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(strings.Join(tree, "\n"), "src/") || !strings.Contains(strings.Join(tree, "\n"), "docs/log.txt") {
		t.Fatalf("unexpected tree %#v", tree)
	}

	stat, err := workspace.Stat("src/pkg/main.go")
	if err != nil {
		t.Fatal(err)
	}
	if stat.Path != "src/pkg/main.go" || stat.IsDir || stat.Size == 0 {
		t.Fatalf("unexpected stat %#v", stat)
	}

	if err := workspace.Edit("src/pkg/main.go", "func main() {}", "func main() { println(\"hi\") }", false); err != nil {
		t.Fatal(err)
	}
	updated, err := os.ReadFile(filepath.Join(root, "src", "pkg", "main.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(updated), "println") {
		t.Fatalf("edit did not update file: %s", string(updated))
	}

	if err := workspace.Delete("docs/log.txt"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "docs", "log.txt")); !os.IsNotExist(err) {
		t.Fatalf("expected deleted file, stat err %v", err)
	}
}

func TestWorkspaceEditRequiresUniqueMatch(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "repeat.txt"), []byte("x\nx\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := workspace.Edit("repeat.txt", "x", "y", false); err == nil {
		t.Fatal("expected non-unique edit to fail")
	}
	if err := workspace.Edit("repeat.txt", "x", "y", true); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, "repeat.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "y\ny\n" {
		t.Fatalf("unexpected replace all result %q", string(data))
	}
}

func TestWorkspaceListsDirectoryEntries(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "README.md"), []byte("hello\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".env.local"), []byte("secret\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(root, "cmd"), 0o755); err != nil {
		t.Fatal(err)
	}

	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}
	entries, err := workspace.List(".")
	if err != nil {
		t.Fatal(err)
	}
	got := strings.Join(entries, "\n")
	for _, want := range []string{"README.md", "cmd/"} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected list output to contain %q, got %#v", want, entries)
		}
	}
	if strings.Contains(got, ".env.local") {
		t.Fatalf("list should hide dotfiles by default, got %#v", entries)
	}
}

func TestWorkspaceDiffTracksOnlyFilesTouchedByAgent(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "agent.txt"), []byte("old\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "external.txt"), []byte("before\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "external.txt"), []byte("after\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := workspace.WriteFile("agent.txt", "new\n"); err != nil {
		t.Fatal(err)
	}

	diff, err := workspace.GitDiff()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(diff, "-old") || !strings.Contains(diff, "+new") {
		t.Fatalf("expected touched file diff, got:\n%s", diff)
	}
	if strings.Contains(diff, "external.txt") || strings.Contains(diff, "before") || strings.Contains(diff, "after") {
		t.Fatalf("diff should ignore untouched external changes, got:\n%s", diff)
	}
}

func TestWorkspaceDiffIncludesNewFilesWrittenByAgent(t *testing.T) {
	root := t.TempDir()
	workspace, err := NewWorkspace(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := workspace.WriteFile("new.txt", "created\n"); err != nil {
		t.Fatal(err)
	}

	diff, err := workspace.GitDiff()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(diff, "+++ b/new.txt") || !strings.Contains(diff, "+created") {
		t.Fatalf("expected new file diff, got:\n%s", diff)
	}
}
